modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="goldenhopper"
version="1.0.0"
displayName="Golden Hopper"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/goldenhopper/update.json"
displayURL="http://mrcrayfish.com/mods?id=goldenhopper"
logoFile="goldenhopper.png"
credits="@Moonshiner99 on Twitter for the mod idea. Pois1x for improved textures!"
authors="MrCrayfish"
description="Simply adds a new golden hopper variant that can filter items, nothing more!"

[[dependencies.goldenhopper]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenhopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"