modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="goldenhopper"
version="1.0.0"
displayName="Golden Hopper"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/goldenhopper/update.json"
displayURL="http://mrcrayfish.com/mods?id=goldenhopper"
logoFile=""
credits="@Moonshiner99 on Twitter for the mod idea"
authors="MrCrayfish"
description="Adds a simple backpack to store more items"

[[dependencies.goldenhopper]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goldenhopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"